### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by carlosflorencio** [lloydstubber/My-WSL-Setup#2]
Hi,

Thanks for sharing your setup. ❤️ 
Can you post any screenshots? 

Hyper had a few bugs in the past, do u have a good experience? 😄 

Thanks!

**Comment by lloydstubber** [comment]
Thanks @iamfreee 

I've just added a screenshot of how it's looking for you. 

The only issue I had with Hyper was their `hyperline` plugin as it wasn't compatible with Windows. So just be weary to check plugin details before installing. Other than that, it's fast and looks great!

Enjoy!
