### ISSUE TITLE
Hi Lloyd, mind if I ask your help on something real quick?

### ISSUE THREAD

**Issue by jcklpe** [lloydstubber/My-WSL-Setup#3]
Your guide is really great! I've been following along and I got to the part where you install your oh-my-zsh theme. I think I've done the same thing (except I'm trying to install the Powerlevel9k theme) but for some reason when I try to use any of the custom prompts that make use of the theme features etc, It throws error codes. I ask you despite the fact that you aren't using the same theme because from what I can see if does look like you're using some kind of powerline inclusive theme. 

 I have the fonts installed and I believe that I have them working in the terminal but when I copy and paste the PowerLevel9k compatible prompt into my zshrc file it does nothing. The same for when I copy it into my bashrc file. BUT when I copy it into my .profile file in place of my current prompt (which is `export PS1="⚡ \[\e[33m\]\w\[\e[m\]\[\e[36;40m\] ⭄\[\e[m\]  "` ) It throws an error saying it doesn't recognize the command. 

Do I need to delete .profile or something so that it will look in my zshrc file instead or something? 

I'm honestly not totally clear on how I'm supposed to be using zsh etc. I believe I have oh-my-zsh working and stuff but it's kind of hard for me to tell tbh

**Comment by jcklpe** [comment]
So I think I figured out part of the problem. Zsh isn't running. I added the stuff to the bashrc and zshrc files as you said but for some reason it only runs zsh when I actually type in "zsh" as a command in the term and then it switches over. Did I miss something?

**Comment by lloydstubber** [comment]
Hey @thedonquixotic, thanks for reaching out and glad you like the guide!

Strange it's not working. Did you put this in your `bashrc`? This will tell the shell to switch to zsh by default.
```
if [ -t 1 ]; then
exec zsh
fi
```

**Comment by jcklpe** [comment]
I did. I figured it out though! I think it was two things. One, I believe I needed to put the if statement to run zsh in my .profile file instead of my bashrc, and I also needed to make sure that VScode was saving the files with a LF instead of CRLF encoding.
