### ISSUE TITLE
¿How to hide /mnt/c/Users/ ?

### ISSUE THREAD

**Issue by j0nl1** [lloydstubber/My-WSL-Setup#4]
Hello, first of all I want to thank you for this guide.
I could set up my zsh enviroment with hyper sucesfully!  
I saw your image and you don't have the prefix part before your username and I want to ask you how you did to hide it??

Thanks again.

This is my setup
![image](https://user-images.githubusercontent.com/40375118/53052715-c4572280-349f-11e9-9667-e94984bdd35d.png)

**Comment by lloydstubber** [comment]
Hi @j0nl1, no problem! Glad you've found it useful. 

Seems like you've got a theme which prints the entire directory out. The standard one I'm using called robbyrussell doesn't do this. I'd recommend making your own custom prompt [here](http://ezprompt.net/) and adding it to your .zshrc file.

Hope that's helpful!
