### ISSUE TITLE
installing packages

### ISSUE THREAD

**Issue by pmonty** [lloydstubber/My-WSL-Setup#5]
One thing I am confused about as a new WSL user is if I should once setup install node, npm, yarn etc.. under wsl using `sudo apt install` or install it in windows now. Does it matter?

**Comment by lloydstubber** [comment]
You need to install whatever it may be via their docs as if it were Linux. For example, if you want Node I opted for nvm, so you can easily switch versions of Node.

You can install nvm via the WSL with: 
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
```

Then follow my instructions so it's setup properly: https://github.com/lloydstubber/my-wsl-setup#install-nvm

**Comment by pmonty** [comment]
Ok cheers! I always thought you needed the stuff installed under windows too. Thanks for clearing that up!
